#!/bin/bash

CONFIG_FILENAME=/boot/config.txt
FIRMWARE_FILENAME=/boot/start.elf
FIRMWARE128_FILENAME=/boot/arm128_start.elf
FIRMWARE192_FILENAME=/boot/arm192_start.elf
FIRMWARE224_FILENAME=/boot/arm224_start.elf
HOSTS_FILENAME=/etc/hosts
HOSTNAME_FILENAME=/etc/hostname

################################################################
function di {
    dialog --output-fd 1 --backtitle "Raspbian configuration" "$@"
}

function reconfig {
    clear
    dpkg-reconfigure "$1"
}

function descr {
    di --title "Description" --yes-label "Proceed" --no-label "Cancel" \
       --yesno "$1" 20 70
}
################################################################
function check_tool {
    command -v "$1" &>/dev/null
}

function check_root {
    whoami | grep '^root$' &>/dev/null
}

function check_error {
    if [ "$1" != 0 ]; then
        echo "Error: $2"
        exit 1
    fi
}

function check_guierror {
    if [ "$1" != 0 ]; then
        di --title "Action result" --msgbox "Error: $2" 5 70
    elif [ "$3" != no_ok ]; then
        di --title "Action result" --msgbox "Success" 5 70
    fi
    return $1
}

function change_config {
    touch $CONFIG_FILENAME
    [ $? -ne 0 ] && return 1

    cp -a -f $CONFIG_FILENAME ${CONFIG_FILENAME}.$(date +%Y%m%d%H%M%S)
    [ $? -ne 0 ] && return 1

    grep "^$1=" $CONFIG_FILENAME &>/dev/null
    if [ $? -eq 0 ]; then
        sed -i "s/^$1=.\\+/$1=$2/" $CONFIG_FILENAME
        [ $? -ne 0 ] && return 1
    else
        echo "$1=$2" >> $CONFIG_FILENAME
        [ $? -ne 0 ] && return 1
    fi
    return 0
}
################################################################
function do_ {
    eval
}

function set_hostname {
    grep "^127.0.0.1" $HOSTS_FILENAME &>/dev/null
    if [ $? -eq 0 ]; then
        sed -i "s/^127.0.0.1\s.\+/127.0.0.1 localhost/" $HOSTS_FILENAME
        check_guierror $? "Unable to change file $HOSTS_FILENAME" no_ok
        [ $? -ne 0 ] && return 1
    else
        echo "127.0.0.1 localhost" >> $HOSTS_FILENAME
        check_guierror $? "Unable to change file $HOSTS_FILENAME" no_ok
        [ $? -ne 0 ] && return 1
    fi

    grep "^127.0.0.1" $HOSTS_FILENAME &>/dev/null
    if [ $? -eq 0 ]; then
        sed -i "s/^127.0.1.1\s.\+/127.0.1.1 $1/" $HOSTS_FILENAME
        check_guierror $? "Unable to change file $HOSTS_FILENAME" no_ok
        [ $? -ne 0 ] && return 1
    else
        echo "127.0.1.1 $1" >> $HOSTS_FILENAME
        check_guierror $? "Unable to change file $HOSTS_FILENAME" no_ok
        [ $? -ne 0 ] && return 1
    fi

    echo "$1" > $HOSTNAME_FILENAME
    check_guierror $? "Couldn't change file $HOSTNAME_FILENAME" no_ok
    [ $? -ne 0 ] && return 1

    hostname "$1"
    check_guierror $? "Hostname command returned error"
    [ $? -ne 0 ] && return 1

    return 0
}
function do_hostname {
    typeset res
    
    descr "This action will change the hostname of the machine."
    [ $? -ne 0 ] && return 1

    res=$(di --inputbox "Enter new hostname:" 20 70)
    [ $? -eq 0 ] && set_hostname "$res"
}

function set_ssh {
    rm -f /etc/ssh/ssh_host_*
    check_guierror $? "Unable to remove files /etc/ssh/ssh_host_*" no_ok
    [ $? -ne 0 ] && return 1

    reconfig openssh-server
    check_guierror $? "Configuration unsuccessful"
}
function do_ssh {
    descr "This action will regenerate the SSH keys of the machine."
    [ $? -eq 0 ] && set_ssh
}

function set_resize {
    descr "This action is not yet supported."
}
function do_resize {
    descr "This action will expand the root partition of the machine to fit the SD card."
    [ $? -eq 0 ] && set_resize
}

function set_timezone {
    reconfig "tzdata"
    check_guierror $? "Configuration unsuccessful" no_ok
}
function do_timezone {
    descr "This action will change the timezone of the machine."
    [ $? -eq 0 ] && set_timezone
}

function set_locales {
    reconfig "locales"
    check_guierror $? "Configuration unsuccessful"
}
function do_locales {
    descr "This action will set the locales configured on the machine."
    [ $? -eq 0 ] && set_locales
}

function set_passwd {
    passwd
    check_guierror $? "Password was not set"
}
function do_passwd {
    descr "This action will change the password of the root user."
    [ $? -eq 0 ] && set_passwd
}

function set_memory {
    typeset filename

    case "$1" in
        "128/128")
            filename=$FIRMWARE128_FILENAME
        ;;
        "192/64")
            filename=$FIRMWARE192_FILENAME
        ;;
        "224/32")
            filename=$FIRMWARE224_FILENAME
        ;;
    esac

    cp -f $filename $FIRMWARE_FILENAME
    check_guierror $? "Unable to copy firmware file $filename"
}
function do_memory {
    typeset res

    descr "This action will change how the RAM is split between the CPU and the GPU."
    [ $? -ne 0 ] && return 1

    res=$(di --menu "Select a memory split (CPU/GPU):" 20 70 3 \
              "128/128" "" \
              "192/64" "" \
              "224/32" "")
    [ $? -eq 0 ] && set_memory "$res"
}

function set_shutdown {
    eval shutdown -${1} now
}
function do_reboot {
    descr "This action will restart your Raspberry Pi."
    [ $? -eq 0 ] && set_shutdown r
}
function do_shutdown {
    descr "This action will shutdown your Raspberry Pi."
    [ $? -eq 0 ] && set_shutdown h
}

function set_upgrade_deb {
    apt-get update && apt-get dist-upgrade
    check_guierror $? "Raspbian upgrade unsuccessful"
}
function do_upgrade_deb {
    descr "This action will upgrade Raspbian to the latest version."
    [ $? -eq 0 ] && set_upgrade_deb
}

function set_upgrade_fw {
    rpi-update
    check_guierror $? "Firmware upgrade unsuccessful"
}
function do_upgrade_fw {
    descr "This action will run the 'rpi-update' script, which updates the kernel and firmware found in /boot."
    [ $? -eq 0 ] && set_upgrade_fw
}

function set_sdtv_mode {
    change_config sdtv_mode "$1"
    check_guierror $? "Setting change unsuccessful"
}
function do_sdtv_mode {
    typeset res

    descr "This action will set the output mode of the composite output."
    [ $? -ne 0 ] && return 1

    res=$(di --cancel-label "Back" --menu "Select a configuration option:" 20 70 12 \
          0 "Normal NTSC (default)" \
          1 "Japanese version of NTSC [no pedestal]" \
          2 "Normal PAL" \
          3 "Brazilian version of PAL [525/60, different subcarrier]" \
         )
    [ $? -eq 0 ] && set_sdtv_mode "$res"
}

function set_sdtv_aspect {
    change_config sdtv_aspect "$1"
    check_guierror $? "Setting change unsuccessful"
}
function do_sdtv_aspect {
    typeset res

    descr "This action will set the aspect ratio of the composite output."
    [ $? -ne 0 ] && return 1

    res=$(di --cancel-label "Back" --menu "Select a configuration option:" 20 70 12 \
          1  "4:3 (default)" \
          2  "14:9" \
          3  "16:9" \
         )
    [ $? -eq 0 ] && set_sdtv_aspect "$res"
}

function set_hdmi_safe {
    change_config hdmi_safe "$1"
    check_guierror $? "Setting change unsuccessful"
}
function do_hdmi_safe {
    typeset res

    descr "This action will override HDMI parameters to safe values, to ensure compatibility:\n \
   - hdmi_force_hotplug=1\n \
   - config_hdmi_boost=4\n \
   - hdmi_group=1\n \
   - hdmi_mode=1\n \
   - disable_overscan=0\n\n \
See http://elinux.org/RPi_config.txt for more information."
    [ $? -ne 0 ] && return 1

    res=$(di --cancel-label "Back" --menu "Select a configuration option:" 20 70 12 \
          0  "Disable HDMI safe mode (default)" \
          1  "Enable HDMI safe mode" \
         )
    [ $? -eq 0 ] && set_hdmi_safe "$res"
}

function set_hdmi_force_hotplug {
    change_config hdmi_force_hotplug "$1"
    check_guierror $? "Setting change unsuccessful"
}
function do_hdmi_force_hotplug {
    typeset res

    descr "This action will force video output over HDMI, even if there is no cable connected."
    [ $? -ne 0 ] && return 1

    res=$(di --cancel-label "Back" --menu "Select a configuration option:" 20 70 12 \
          0  "Use composite video if no cable is connected (default)" \
          1  "Force video over HDMI if no cable is connected" \
         )
    [ $? -eq 0 ] && set_hdmi_force_hotplug "$res"
}

function set_hdmi_drive {
    change_config hdmi_drive "$1"
    check_guierror $? "Setting change unsuccessful"
}
function do_hdmi_drive {
    typeset res

    descr "This action will select the video format format used over the HDMI output."
    [ $? -ne 0 ] && return 1

    res=$(di --cancel-label "Back" --menu "Select a configuration option:" 20 70 12 \
          0  "Normal DVI mode [without sound]" \
          1  "Normal HDMI mode [with sound if supported]" \
         )
    [ $? -eq 0 ] && set_hdmi_drive "$res"
}

function set_hdmi_resolution {
    if [ "${1:0:3}" = cea ]; then
        change_config hdmi_group 1 #TODO: check
    else
        change_config hdmi_group 2 #TODO: check
    fi
    check_guierror $? "Setting change unsuccessful" no_ok

    change_config hdmi_mode "${1:3:2}"
    check_guierror $? "Setting change unsuccessful"
}
function do_hdmi_resolution {
    typeset res

    descr "This action will select the screen resolution of the HDMI output.\n \
  H  means 16:9 variant (of a normally 4:3 mode).\n \
  2x means pixel doubled (i.e. higher clock rate, with each pixel repeated twice)\n \
  4x means pixel quadrupled (i.e. higher clock rate, with each pixel repeated four times)"
    [ $? -ne 0 ] && return 1

    res=$(di --cancel-label "Back" --menu "Select a configuration option:" 20 70 25 \
          cea1    "VGA" \
          cea2    "480p  60Hz" \
          cea3    "480p  60Hz  H" \
          cea4    "720p  60Hz" \
          cea5    "1080i 60Hz" \
          cea6    "480i  60Hz" \
          cea7    "480i  60Hz  h" \
          cea8    "240p  60Hz" \
          cea9    "240p  60Hz  h" \
          cea10   "480i  60Hz  4x" \
          cea11   "480i  60Hz  4x h" \
          cea12   "240p  60Hz  4x" \
          cea13   "240p  60Hz  4x h" \
          cea14   "480p  60Hz  2x" \
          cea15   "480p  60Hz  2x h" \
          cea16   "1080p 60Hz" \
          cea17   "576p  50Hz" \
          cea18   "576p  50Hz  h" \
          cea19   "720p  50Hz" \
          cea20   "1080i 50Hz" \
          cea21   "576i  50Hz" \
          cea22   "576i  50Hz  h" \
          cea23   "288p  50Hz" \
          cea24   "288p  50Hz  h" \
          cea25   "576i  50Hz  4x" \
          cea26   "576i  50Hz  4x h" \
          cea27   "288p  50Hz  4x" \
          cea28   "288p  50Hz  4x h" \
          cea29   "576p  50Hz  2x" \
          cea30   "576p  50Hz  2x h" \
          cea31   "1080p 50Hz" \
          cea32   "1080p 24Hz" \
          cea33   "1080p 25Hz" \
          cea34   "1080p 30Hz" \
          cea35   "480p  60Hz  4x" \
          cea36   "480p  60Hz  4xh" \
          cea37   "576p  50Hz  4x" \
          cea38   "576p  50Hz  4x h" \
          cea39   "1080i 50Hz  reduced blanking" \
          cea40   "1080i 100Hz" \
          cea41   "720p  100Hz" \
          cea42   "576p  100Hz" \
          cea43   "576p  100Hz h" \
          cea44   "576i  100Hz" \
          cea45   "576i  100Hz h" \
          cea46   "1080i 120Hz" \
          cea47   "720p  120Hz" \
          cea48   "480p  120Hz" \
          cea49   "480p  120Hz h" \
          cea50   "480i  120Hz" \
          cea51   "480i  120Hz h" \
          cea52   "576p  200Hz" \
          cea53   "576p  200Hz h" \
          cea54   "576i  200Hz" \
          cea55   "576i  200Hz h" \
          cea56   "480p  240Hz" \
          cea57   "480p  240Hz h" \
          cea58   "480i  240Hz" \
          cea59   "480i  240Hz h" \
          dmt1    "640x350   85Hz" \
          dmt2    "640x400   85Hz" \
          dmt3    "720x400   85Hz" \
          dmt4    "640x480   60Hz" \
          dmt5    "640x480   72Hz" \
          dmt6    "640x480   75Hz" \
          dmt7    "640x480   85Hz" \
          dmt8    "800x600   56Hz" \
          dmt9    "800x600   60Hz" \
          dmt10   "800x600   72Hz" \
          dmt11   "800x600   75Hz" \
          dmt12   "800x600   85Hz" \
          dmt13   "800x600   120Hz" \
          dmt14   "848x480   60Hz" \
          dmt16   "1024x768  60Hz" \
          dmt17   "1024x768  70Hz" \
          dmt18   "1024x768  75Hz" \
          dmt19   "1024x768  85Hz" \
          dmt20   "1024x768  120Hz" \
          dmt21   "1152x864  75Hz" \
          dmt22   "1280x768        reduced blanking" \
          dmt23   "1280x768  60Hz" \
          dmt24   "1280x768  75Hz" \
          dmt25   "1280x768  85Hz" \
          dmt26   "1280x768  120Hz reduced blanking" \
          dmt27   "1280x800        reduced blanking" \
          dmt28   "1280x800  60Hz" \
          dmt29   "1280x800  75Hz" \
          dmt30   "1280x800  85Hz" \
          dmt31   "1280x800  120Hz reduced blanking" \
          dmt32   "1280x960  60Hz" \
          dmt33   "1280x960  85Hz" \
          dmt34   "1280x960  120Hz reduced blanking" \
          dmt35   "1280x1024 60Hz" \
          dmt36   "1280x1024 75Hz" \
          dmt37   "1280x1024 85Hz" \
          dmt38   "1280x1024 120Hz reduced blanking" \
          dmt39   "1360x768  60Hz" \
          dmt40   "1360x768  120Hz reduced blanking" \
          dmt41   "1400x1050       reduced blanking" \
          dmt42   "1400x1050 60Hz" \
          dmt43   "1400x1050 75Hz" \
          dmt44   "1400x1050 85Hz" \
          dmt45   "1400x1050 120Hz reduced blanking" \
          dmt46   "1440x900        reduced blanking" \
          dmt47   "1440x900  60Hz" \
          dmt48   "1440x900  75Hz" \
          dmt49   "1440x900  85Hz" \
          dmt50   "1440x900  120Hz reduced blanking" \
          dmt51   "1600x1200 60Hz" \
          dmt52   "1600x1200 65Hz" \
          dmt53   "1600x1200 70Hz" \
          dmt54   "1600x1200 75Hz" \
          dmt55   "1600x1200 85Hz" \
          dmt56   "1600x1200 120Hz reduced blanking" \
          dmt57   "1680x1050       reduced blanking" \
          dmt58   "1680x1050 60Hz" \
          dmt59   "1680x1050 75Hz" \
          dmt60   "1680x1050 85Hz" \
          dmt61   "1680x1050 120Hz reduced blanking" \
          dmt62   "1792x1344 60Hz" \
          dmt63   "1792x1344 75Hz" \
          dmt64   "1792x1344 120Hz reduced blanking" \
          dmt65   "1856x1392 60Hz" \
          dmt66   "1856x1392 75Hz" \
          dmt67   "1856x1392 120Hz reduced blanking" \
          dmt68   "1920x1200       reduced blanking" \
          dmt69   "1920x1200 60Hz" \
          dmt70   "1920x1200 75Hz" \
          dmt71   "1920x1200 85Hz" \
          dmt72   "1920x1200 120Hz reduced blanking" \
          dmt73   "1920x1440 60Hz" \
          dmt74   "1920x1440 75Hz" \
          dmt75   "1920x1440 120Hz reduced blanking" \
          dmt76   "2560x1600       reduced blanking" \
          dmt77   "2560x1600 60Hz" \
          dmt78   "2560x1600 75Hz" \
          dmt79   "2560x1600 85Hz" \
          dmt80   "2560x1600 120Hz reduced blanking" \
          dmt81   "1366x768  60Hz" \
          dmt82   "1080p     60Hz" \
          dmt83   "1600x900        reduced blanking" \
          dmt84   "2048x1152       reduced blanking" \
          dmt85   "720p      60Hz" \
          dmt86   "1366x768        reduced blanking" \
         )
    [ $? -eq 0 ] && set_hdmi_resolution "$res"
}

function set_hdmi_boost {
    change_config hdmi_boost "$1"
    check_guierror $? "Setting change unsuccessful"
}
function do_hdmi_boost {
    typeset res

    descr "This action will boost the strength of the HDMI signal, in case there are interferences."
    [ $? -eq 0 ] && return 1

    res=$(di --cancel-label "Back" --menu "Select a configuration option:" 20 70 12 \
          0  "No boost (default)" \
          4  "Medium boost" \
          7  "Maximum boost" \
         )
    [ $? -eq 0 ] && set_hdmi_boost "$res"
}

function set_reset_video {
    mv $CONFIG_FILENAME ${CONFIG_FILENAME}.$(date +%Y%m%d%H%M%S)
    check_guierror $? "Unable to delete $CONFIG_FILENAME"
}
function do_reset_video {
    typeset res

    descr "This action will reset the video settings to their defaults by deleting $CONFIG_FILENAME."
    [ $? -eq 0 ] && set_reset_video
}

################################################################
check_root
check_error $? "you must be root to use this program"

check_tool dialog
check_error $? "this script requires 'dialog'. try 'sudo apt-get install dialog'."

check_tool rpi-update
check_error $? "This script requires 'rpi-update'. Please try installing it."

while [ 1 ]; do
    res=$(di --cancel-label "Exit" --menu "Select a configuration option:" 20 70 12 \
    	  hostname    "Change hostname" \
    	  resize      "Resize partition to fill SD card" \
    	  timezone    "Configure local timezone" \
    	  locales     "Set locales" \
    	  passwd      "Change root password" \
    	  memory      "Change memory allocation" \
          upgrade_deb "Upgrade Raspbian" \
          upgrade_fw  "Upgrade Raspberry Pi firmware" \
          video       "Change video settings" \
          reboot      "Reboot" \
          shutdown    "Shutdown" \
         )
    [ $? -ne 0 ] && break

    if [ "$res" = "video" ]; then
        while [ 1 ]; do
            res=$(di --cancel-label "Back" --menu "Select a configuration option:" 20 70 12 \
                  sdtv_mode          "TV standard for composite output" \
                  sdtv_aspect        "Aspect ratio for composite output" \
                  hdmi_safe          "Enable maximum HDMI compatibility settings" \
                  hdmi_force_hotplug "Force HDMI as default source" \
                  hdmi_drive         "Choose HDMI or DVI mode" \
                  hdmi_resolution    "Define the screen resolution" \
                  reset_video        "Reset video options" \
                 )
            [ $? -ne 0 ] && break
            eval do_${res} 
        done
    else
        eval do_${res} 
    fi
done

clear

exit 0

